version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - static:/app/result_build/build/

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
      network: host
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static:/static/
      - media:/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
